services:
  - type: web
    name: Lung-Cancer-Classification
    env: docker
    repo: https://github.com/Sazibul-Islam-Siam/Lung-Cancer-Classification
    branch: main
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: FLASK_DEBUG
        value: "0"
      - key: MODEL_URL
        value: "" # Optional: set a URL to download model at runtime (recommended)
